apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-fastapi
  template:
    metadata:
      labels:
        app: mlops-fastapi
    spec:
      containers:
        - name: mlops-fastapi
          image: 949829287785.dkr.ecr.us-east-1.amazonaws.com/mlops-fastapi-app:latest
          ports:
            - containerPort: 8000

